server:
  port: 8080

spring:
  application:
    name: claimtrace-iam

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/claimtrace_iam}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: 2000ms

claimtrace:
  jwt:
    # 256-bit HMAC secret
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 1800000 # 30 minutes in milliseconds (30 * 60 * 1000)

logging:
  level:
    root: INFO
    com.claimtrace.iam: DEBUG
    org.springframework.security: INFO
